### ISSUE TITLE
Support both the Country Name and the Country ID 

### ISSUE THREAD

**Issue by TimCummins** [bullhorn/dataloader#101]
Current version defaults to 'US' when using country codes in ClientContact address.countryID. It would be useful if both code & name is supported.

**Comment by ndickerson** [comment]
Thanks Tim for submitting this issue!  After a team discussion, we determined that since the Bullhorn internal `countryID` is not an existing standard, but unique to Bullhorn, we don't want to support the setting of a `countryID` value directly. Instead, we have [documented the behavior](https://github.com/bullhorn/dataloader/wiki/FAQs#q-how-do-i-set-the-addresscountryid-field) in the FAQs and the next release of DataLoader will have example files that reflect the full country name for the `countryID` field.
