### ISSUE TITLE
One record not indexed on insert

### ISSUE THREAD

**Issue by davidrendall** [bullhorn/dataloader#110]
Hello again. I've been inserting a few client corporation and client contact records using DataLoader. So far, I have added 15 client corporation records, all of which are listed in my DataLoader results as successfully inserted. One record, ID 13, is not visible in the Bullhorn web UI. When I try to insert client contact records for that client corporation, I get an error that the client corporation doesn't exist on Bullhorn. I checked that client corp ID 13 exists on Bullhorn by issuing a "query" command via Postman; the query returned the details of client corp 13 OK. However, when I issued a "search" command via Postman, no results were returned. So it looks as though that one record was not indexed for some reason. But that prevents the client contacts being inserted. Are there any reasons why the indexing would have failed on this one record? Is there any to force the DataLoader to use a "query" rather than a "search" to get the client corp?

**Comment by ndickerson** [comment]
Hi David, I'm not sure why that one record would have issues being indexed. Have you tried isolating the various data fields in that record to see if there's some particular field that's causing indexing to fail?

We've been discussing possible long term solutions for improving our reliance on the index for associating data. We have discussed the possibility of locally caching the external to internal ID references so that they can be used later on instead of hitting the index. It's still a ways off, and we haven't started any development on this, but it could solve this particular situation (though the Company List in Bullhorn would still be missing that Company record).

**Comment by davidrendall** [comment]
Thanks Nathan. That record is not different from the others in any significant way. It has the same fields populated, no unusual characters and no relationships with other objects (apart from address, but the other records have that too). Is there any way of getting an error message from the indexer?

**Comment by ndickerson** [comment]
As a developer, I don't have access to error messages from indexers in prod. If you are able to work with our support team to get an answer about that indexing issue, I would be interested to know what is causing it. This issue appears to be outside the scope of DataLoader, since we are only a consumer of the REST API, and the REST API did not report any errors.

**Comment by davidrendall** [comment]
Thanks Nathan, I'll raise a Jira ticket and I'll let you know what the response is.

**Comment by davidrendall** [comment]
BTO-5769. No idea if that is the right team, but hopefully they will know how to route it.

**Comment by ndickerson** [comment]
Thanks David, I'll mark this issue as closed now that the Jira ticket has been created. We'll be addressing indexing performance in future releases of DataLoader, and we'll keep an eye out for issues like this as we go.
