### ISSUE TITLE
Note personReference

### ISSUE THREAD

**Issue by davidrendall** [bullhorn/dataloader#111]
Hello again. I've been trying to load some notes. A value for personReference is required, but I don't know what this should be? In your example, you have personReference.name as the field name and "Manager CorporateUser" as the example value. PersonReference doesn't seem to have an ExternalID field, so I guess it can't be the candidate/contact. The commentingUserID is in a different field and is also required (I've set it to Unassigned). If it's not the candidate and it's not the commenting user, I don't see what else the PersonReference could be...? Thanks again for your help.

**Comment by ndickerson** [comment]
Hi David, `Note.personReference` and `Note.commentingUser` are of type: `Person`, which is a very flexible field which can be assigned to a `CorporateUser`, `Candidate`, `Contact`, `Lead`, or any `Person` in the CRM.  The catch is that only the shared fields are included, and since `externalID` is missing from some people objects, that one cannot be used.  However, custom fields such as `customText1` can be used.  You can use something like, `.id`, `.name`, `.email`, or `customText1`.

Here's what the REST Documentation Says: http://developer.bullhorn.com/sites/default/files/BullhornRESTAPI_0.pdf

`personReference`: To-one association. Person with whom this Note is associated.

`commentingPerson`: To-one association. Person who created the Note. The default value is user who creates the Note. (In this case the login used in DataLoader)

Here's an example file I just created that works by targeting an email from a corporate user, and a customText1 field from a lead (could be a candidate, or any person entity):
```
personReference.email,commentingPerson.customText1,comments
manager.corporateuser@test.com,lead-ext-2,Test Note 12345
```

After I create the note (with id=95 from inspecting the DataLoader results file), I made this call:
{{RESTURL}}/entity/Note/95?fields=id,commentingPerson,comments,personReference

And here's the REST response:
```
{
  "data": {
    "id": 95,
    "commentingPerson": {
      "id": 36,
      "_subtype": "Lead"
    },
    "comments": "Test Note 12345",
    "personReference": {
      "id": 5,
      "_subtype": "CorporateUser"
    }
  }
}
```

Does that help answer your question?

**Comment by davidrendall** [comment]
Thanks Nathan. Yes, that answers my question. I will look at putting something in a customText field. I don't want the migration to be a multi-step process if I can avoid it.

**Comment by ndickerson** [comment]
Cool, I will go ahead and close this issue!
