### ISSUE TITLE
Candidate Entity: Job Function Field is getting updated randomly for few records when Status field is updated using data loader in BH Staging

### ISSUE THREAD

**Issue by Shamshadbegam** [bullhorn/dataloader#332]
### Description
Candidate Entity: Job Function Field is getting updated randomly for few records when Status field is updated using data loader in BH Staging

[Description of the issue]
Candidate Entity: Job Function Field is getting updated randomly for few records when Status field is updated using data loader in BH Staging

Please find below sample LegacyId of candidate Entity where Job Function was modified to Other when Status was updated using data loader

1. 18050932

Please find below sample LegacyId of candidate Entity where Job Function was not modified when Status was updated using data loader
1.18056095

Please find below sample LegacyId of candidate Entity where Job Function was modified when Status was updated using data loader
1.18050932

### Steps to Reproduce
1. Do a first run with the dataloader where you duplicate check on "candidateExistField=externalID"
2. The dataloader should tell you that it updated records successfully, but when you look in the system along with Status field Update, Job Function field also is updated for few reords

Request you to check on this and provide your inputs on the same.

[Candidate_Clarification_On_JobFunction_Field_Update.docx](https://github.com/bullhorn/dataloader/files/5428004/Candidate_Clarification_On_JobFunction_Field_Update.docx)

##### Expected behavior:

[What you expect to happen]

##### Actual behavior:

[What actually happens]

##### Reproduces how often:

[What percentage of the time does it reproduce?]

### Additional Information

1. The `dataloader.properties` file (minus login info)
2. The CSV input file (smallest possible file that reproduces the issue)
3. The results file(s)
4. The log file

**Comment by ndickerson** [comment]
Sorry, I cannot triage this issue as is since the required data is not filled out. 

Please attach for a single run of the Data Loader: 
1. the inputs file
2. the results file(s)
3. the log file

The Data Loader translates CSV data into Rest API calls, and if there are potential bugs, I need to examine the log file to piece back together exactly which rest calls were made. Unless I can see the calls being made, I'm not sure how to help with: `Job Function field also is updated for few reords`.

**Comment by Shamshadbegam** [comment]
Hi Nathan,

Please find the attached which has input files, result files and log files.

[Extract.zip](https://github.com/bullhorn/dataloader/files/5429064/Extract.zip)

Thanks,
Shamshad

**Comment by ndickerson** [comment]
The provided CSV input files have two columns: `externalID` (for identifying and updating a candidate) and `status`. That all looks correct, and the Data Loader is updating status fields.

You mention that the issue is: "Candidate Entity: Job Function Field is getting updated randomly for few records when Status field is updated using data loader in BH Staging"

Which specific field are you referring to when you say: "Job Function". I'm almost certain that this is unrelated to the work that's being done in Data Loader, since Data Loader is just updating a status on the given candidate records. 

You'll need to narrow down the issue to a single reproducable record in order to understand what's happening.

**Comment by Shamshadbegam** [comment]
Thanks a lot for the update Nathan..
