### ISSUE TITLE
Display values not converting to back end database values

### ISSUE THREAD

**Issue by miola03** [bullhorn/dataloader#358]
### Steps to Reproduce
Given the placement field mapping for terminationReason of:
- display value of 'Abandonment' that maps to the value list value of 'SAB'
- display value of 'Compliance Failure' that maps to the value list value of 'SCF'

1. Using DataLoader to update a placement record terminationReason Display Value from 'Abandonment' to 'Compliance'

##### Expected behavior:

I would expect the display value to update to 'Compliance' which it does but i would also expect the Datamirror value to show 'SCF'.

##### Actual behavior:

The actual behavior of making this update inputs the value list as 'Compliance' in DataMirror instead of 'SCF'. 

##### Reproduces how often:

Every time

### Additional Information

N/A

**Comment by ndickerson** [comment]
This is the intended behavior. Display values are configured via field maps, while only the actual values are what are communicated via REST and stored in the database. The Data Loader is converting the provided spreadsheet data into REST calls, and it does so by communicating the underlying values. Data Loader has no awareness of what display values have been configured via field maps for any given user. 

To pull off this feature request would require additional complexity in Data Loader in order to lookup field maps and validate the provided display names and additional configuration. For now, you can convert the display values to their underlying values in the spreadsheet before loading.
