### ISSUE TITLE
Question around export

### ISSUE THREAD

**Issue by nysthee** [bullhorn/dataloader#364]
### Description

Hi,

For our use case, we would like to do a bulk export of a given entity so we can clean data in a batch. Is this use case supported in the current version of the tool? As per my understanding. The export command is only able to export rows for entities where you already have a ref id/column in a local CSV file. How would one generate such a file with let's say a sample of 1000 random entity rows?

**Comment by ndickerson** [comment]
If you would like to export everything, you'll just need to know what the bullhorn IDs are for the entities you care about. You can do some REST API queries to determine the min/max values of internal IDs, since they are sequential, then create an export file with every column you care about, and enter IDs 1 through 1,000 for instance.

**Comment by nysthee** [comment]
Thanks for your reply!
