### ISSUE TITLE
2.0.0 ClientContact Categories required on update

### ISSUE THREAD

**Issue by ccoffman1** [bullhorn/dataloader#71]
It seems to have started with 2.0.0 but when making an update to ClientContacts it will error out unless you also include category in the update as well (I updated with category.name).

So, for example, in REST (and in 1.4 / 1.0.2 I believe) you can update a ClientContact's status and id alone.  To do it in 2.0.0 you need status, id, and category.

**Comment by ndickerson** [comment]
Hi Colin, I'm not able to reproduce the error you're seeing on v2.0.0.  Can you please update this issue with the header and first row of the CSV file you're working with?  Here's what I'm able to do using version 2.0.0:

The minimum required CSV to **insert** a ClientContact record:
```
clientCorporation.externalID
                           1
```
The only thing that's required is the clientCorporation lookup (can use any field, here I'm using externalID because that's the preferred path for associating to parent records).

A more realistic version for performing a future update.
```
clientCorporation.externalID,           name,   status, externalID
                           1, Test Candidate, New Lead,       1001
```

The minimum required CSV to **update** a ClientContact record:
```
externalID, status
      1001, Active
```
Note that in order to update, an exist field is required in the dataloader.properties file, here I'm using: 

```
clientContactExistField=externalID
```

Without the clientContactExistField being set, the call will always insert, never update.

**Comment by ccoffman1** [comment]
I ran a presentation in front of 20 people on a conference room computer and it happened.  Reran it back at my own desk and it worked without issue.  I ran the same process.  Oh well, glad it isn't a real issue.

Thank you for your efforts!
